In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd


def fetch_apt_sale_data(service_key, gu_code, date, n):
    """
    Fetch apartment transaction data from OpenAPI and return it as a cleaned DataFrame.

    Args:
        service_key(str) : The API key needed to access the service.
        gu_code (int) : The code of the district (구).
        date (int) : The date in the format YYYYMM.
        n (int) : The number of rows to fetch.

    Returns:
        pd.DataFrame: A DataFrame containing cleaned apartment data.
    """

    # Construct the URL
    url = f'https://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade?serviceKey={service_key}&'\
          f'LAWD_CD={gu_code}&'\
          f'DEAL_YMD={date}&'\
          f'numOfRows={n}'

    # Request data from the API
    result = urlopen(url)
    house = BeautifulSoup(result, 'lxml')
    te = house.find_all('item')

    # Parse the data
    datas = []
    for i in range(len(te)):
        apt_name = te[i].aptnm.string.strip()
        apt_userArea = te[i].excluusear.string.strip()
        apt_floor = te[i].floor.string.strip()
        apt_buildYear = te[i].buildyear.string.strip()
        deal_amount = te[i].dealamount.string.strip()
        deal_year = te[i].dealyear.string.strip()
        deal_month = te[i].dealmonth.string.strip()
        deal_day = te[i].dealday.string.strip()
        dong_name = te[i].umdnm.string.strip()
        gu_code = te[i].sggcd.string.strip()


        data = [dong_name, apt_name, apt_userArea, apt_floor, deal_amount, deal_year, deal_month, deal_day, gu_code, apt_buildYear]
        datas.append(data)

    # Create DataFrame
    df = pd.DataFrame(datas, columns = ['dong_name', 'apt_name', 'apt_userArea', 'apt_floor', 'deal_amount', 'deal_year', 'deal_month', 'deal_day', 'gu_code', 'apt_buildYear'])

    # Clean and convert data types
    df['apt_userArea'] = df['apt_userArea'].astype(float)
    df['apt_floor'] = df['apt_floor'].astype(int)
    df['apt_buildYear'] = df['apt_buildYear'].astype(int)
    df['deal_amount'] = df['deal_amount'].str.replace(',','').astype(int)
    df['deal_year'] = df['deal_year'].astype(int)
    df['deal_month'] = df['deal_month'].astype(int)
    df['deal_day'] = df['deal_day'].astype(int)
    df['gu_code'] = df['gu_code'].astype(int)

    return df

# Example usage
service_key = "sgOQlwpackhO01oaCAAcwfJy4IGwN%2F2uLcXifUcmx%2FIwLRwPkaBTgz9kBtg5oQg8YRxPZICHxtKF%2BsXKn4rf%2Fw%3D%3D"
gu_code = 11680 #강남구 코드
date = 202501 #오늘 날짜로??
n = 10000 #개수만큼나오게 하기

# Fetch data
df = fetch_apt_sale_data(service_key, gu_code, date, n)

# Print head of the DataFrame
df

C:\Users\yoonh\AppData\Local\Temp\ipykernel_22364\2428769895.py:28: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  house = BeautifulSoup(result, 'lxml')

,dong_name,apt_name,apt_userArea,apt_floor,deal_amount,deal_year,deal_month,deal_day,gu_code,apt_buildYear
0,도곡동,대우디오빌,25.8900,6,24800,2025,1,31,11680,2004
1,역삼동,역삼푸르지오,84.9097,10,270000,2025,1,25,11680,2006
2,도곡동,경남,59.7600,4,161000,2025,1,25,11680,2005
3,세곡동,세곡푸르지오,84.8400,13,160000,2025,1,24,11680,2012
4,도곡동,도곡렉슬,120.8233,15,363000,2025,1,16,11680,2006
...,...,...,...,...,...,...,...,...,...,...
121,삼성동,석탑아파트101동,59.8200,8,162500,2025,1,7,11680,1996
122,대치동,쌍용대치2,84.4900,11,294000,2025,1,9,11680,1983
123,대치동,대우아이빌명문가(891-23),34.2000,8,25000,2025,1,3,11680,2004
124,논현동,아크로힐스논현,84.0740,18,240000,2025,1,3,11680,2014
125,역삼동,래미안그레이튼,142.0600,7,338000,2025,1,2,11680,2009

In [58]:
!jupyter nbconvert --to script 매매가.ipynb

[NbConvertApp] Converting notebook 매매가.ipynb to script
[NbConvertApp] Writing 2778 bytes to 매매가.py