In [1]:


def fetch_apt_rent_data(service_key, gu_code, date, n):

    from urllib.request import urlopen
    from bs4 import BeautifulSoup
    import pandas as pd
    """
    Fetch apartment rental transaction data from OpenAPI and return it as a cleaned DataFrame.

    Args:
        service_key(str) : The API key needed to access the service.
        gu_code (int) : The code of the district (구).
        date (int) : The date in the format YYYYMM.
        n (int) : The number of rows to fetch.

    Returns:
        pd.DataFrame: A DataFrame containing cleaned apartment data.
    """
    # Construct the URL
    url = f'https://apis.data.go.kr/1613000/RTMSDataSvcAptRent/getRTMSDataSvcAptRent?LAWD_CD={gu_code}&'\
        f'DEAL_YMD={date}&'\
        f'serviceKey={service_key}&'\
        f'numOfRows={n}'

    # Request data from the API
    result = urlopen(url)
    house = BeautifulSoup(result, 'lxml')
    te = house.find_all('item')

    # Parse the data
    datas = []
    for i in range(len(te)):
        apt_name = te[i].aptnm.string.strip()
        apt_userArea = te[i].excluusear.string.strip()
        apt_floor = te[i].floor.string.strip()
        apt_buildYear = te[i].buildyear.string.strip()
        deal_deposit = te[i].deposit.string.strip()
        deal_rent = te[i].monthlyrent.string.strip()
        deal_year = te[i].dealyear.string.strip()
        deal_month = te[i].dealmonth.string.strip()
        deal_day = te[i].dealday.string.strip()
        dong_name = te[i].umdnm.string.strip()
        gu_code = te[i].sggcd.string.strip()

        data = [dong_name, apt_name, apt_userArea, apt_floor, deal_deposit, deal_rent , deal_year, deal_month, deal_day, gu_code, apt_buildYear]
        datas.append(data)

    # Create DataFrame
    df = pd.DataFrame(datas, columns = ['dong_name', 'apt_name', 'apt_userArea', 'apt_floor', 'deal_deposit', 'deal_rent', 'deal_year', 'deal_month', 'deal_day', 'gu_code', 'apt_buildYear'])

    # Clean and convert data types
    df['apt_userArea'] = df['apt_userArea'].astype(float)
    df['apt_floor'] = df['apt_floor'].astype(int)
    df['apt_buildYear'] = df['apt_buildYear'].astype(int)
    df['deal_deposit'] = df['deal_deposit'].str.replace(',','').astype(int)
    df['deal_rent'] = df['deal_rent'].str.replace(',','').astype(int)
    df['deal_year'] = df['deal_year'].astype(int)
    df['deal_month'] = df['deal_month'].astype(int)
    df['deal_day'] = df['deal_day'].astype(int)
    df['gu_code'] = df['gu_code'].astype(int)

    return df

# Example usage
service_key = "sgOQlwpackhO01oaCAAcwfJy4IGwN%2F2uLcXifUcmx%2FIwLRwPkaBTgz9kBtg5oQg8YRxPZICHxtKF%2BsXKn4rf%2Fw%3D%3D"
gu_code = 11680
date = 202501
n = 10000

# Fetch data
df = fetch_apt_rent_data(service_key, gu_code, date, n)

# Print head of the DataFrame
df

C:\Users\yoonh\AppData\Local\Temp\ipykernel_6652\2821650835.py:26: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  house = BeautifulSoup(result, 'lxml')

,dong_name,apt_name,apt_userArea,apt_floor,deal_deposit,deal_rent,deal_year,deal_month,deal_day,gu_code,apt_buildYear
0,대치동,한보미도맨션1,84.480,2,82950,0,2025,1,14,11680,1983
1,압구정동,현대8차(성수현대:91~95동),111.500,11,60000,100,2025,1,4,11680,1980
2,대치동,은마,76.790,14,80000,0,2025,1,10,11680,1979
3,수서동,신동아,33.180,13,30000,0,2025,1,22,11680,1992
4,일원동,디에이치자이개포,63.760,2,70000,240,2025,1,20,11680,2021
...,...,...,...,...,...,...,...,...,...,...,...
1133,대치동,"대치우성아파트1동,2동,3동,5동,6동,7동",84.690,13,70000,70,2025,1,2,11680,1984
1134,청담동,청담자이,49.619,11,110000,0,2025,1,2,11680,2011
1135,대치동,대치현대,85.000,10,97600,0,2025,1,2,11680,1999
1136,개포동,개포자이프레지던스,84.600,6,50000,272,2025,1,2,11680,2023
1137,일원동,목련타운,99.790,14,75000,78,2025,1,2,11680,1993

In [13]:
!jupyter nbconvert --to script 전월세.ipynb

[NbConvertApp] Converting notebook 전월세.ipynb to script
[NbConvertApp] Writing 2894 bytes to 전월세.py